environment:
  matrix:
    - VS_NAME: Visual Studio 2015
      VS_VERSION: 14 2015
      ARCH: Win32

    - VS_NAME: Visual Studio 2015
      VS_VERSION: 14 2015
      ARCH: x64

    - VS_NAME: Visual Studio 2017
      VS_VERSION: 15 2017
      ARCH: Win32

    - VS_NAME: Visual Studio 2017
      VS_VERSION: 15 2017
      ARCH: x64

    - VS_NAME: Visual Studio 2019
      VS_VERSION: 16 2019
      ARCH: Win32

    - VS_NAME: Visual Studio 2019
      VS_VERSION: 16 2019
      ARCH: x64

configuration:
  - Debug
  - Release

before_build: |
  cd pqalgo/tests
  dir "C:/Program Files (x86)"
  dir "C:/Program Files (x86)/Microsoft Visual Studio"
  cmake -S . -B build -G "Visual Studio %VS_VERSION%" -A %ARCH%
  cd build
  dir

build:
  project: pqalgo/tests/build/sorttest.sln
  parallel: true
  verbosity: minimal

test_script:
  - dir
  - .\\Debug\\app.exe
