environment:
  matrix:
    - VS_NAME: Visual Studio 2015
      VS_VERSION: 14 2015
      ARCH: Win32

    - VS_NAME: Visual Studio 2015
      VS_VERSION: 14 2015
      ARCH: x64

    - VS_NAME: Visual Studio 2017
      VS_VERSION: 15 2017
      ARCH: Win32

    - VS_NAME: Visual Studio 2017
      VS_VERSION: 15 2017
      ARCH: x64

    - VS_NAME: Visual Studio 2019
      VS_VERSION: 16 2019
      ARCH: Win32

    - VS_NAME: Visual Studio 2019
      VS_VERSION: 16 2019
      ARCH: x64

configuration:
  - Debug

before_build:
  - cd pqalgo/tests
  - dir
  - cmake -S . -B build -G "Visual Studio %VS_VERSION%" -A %ARCH%
  - dir
  - cd build

build:
  project: sorttest.sln
  parallel: true
  verbosity: minimal

test_script:
  - dir
  - .\\Debug\\app.exe
