configuration:
  - Debug

environment:
  matrix:
    - VS_NAME: Visual Studio 2015
      VS_VERSION: 14 2015
      ARCH: win32

    - VS_NAME: Visual Studio 2015
      VS_VERSION: 14 2015
      ARCH: x64

    - VS_NAME: Visual Studio 2017
      VS_VERSION: 15 2017
      ARCH: win32

    - VS_NAME: Visual Studio 2017
      VS_VERSION: 15 2017
      ARCH: x64

    - VS_NAME: Visual Studio 2019
      VS_VERSION: 16 2019
      ARCH: win32

    - VS_NAME: Visual Studio 2019
      VS_VERSION: 16 2019
      ARCH: x64

before_build:
  - cd pqalgo/tests
  - cmake -DCMAKE_GENERATOR_PLATFORM=%ARCH% . -G "Visual Studio %VS_VERSION%"

build:
  project: sorttest.sln
  parallel: true
  verbosity: minimal

test_script:
  - dir
  - .\\Debug\\app.exe
