environment:
  # 缺少 Visual Studio 15 2017 环境
  matrix:
    - VS_NAME: Visual Studio 2015
      VS_VERSION: 14 2015
      ARCH: Win32

    - VS_NAME: Visual Studio 2015
      VS_VERSION: 14 2015
      ARCH: x64

    - VS_NAME: Visual Studio 2019
      VS_VERSION: 16 2019
      ARCH: Win32

    - VS_NAME: Visual Studio 2019
      VS_VERSION: 16 2019
      ARCH: x64

configuration:
  - Debug
  - Release

before_build: |
  dir "C:\Program Files"
  dir "C:\Program Files (x86)"
  dir "C:\Program Files (x86)\Microsoft Visual Studio"
  cd pqalgo/tests
  cmake -S . -B build -G "Visual Studio %VS_VERSION%" -A %ARCH%

build:
  project: pqalgo/tests/build/sorttest.sln
  parallel: true
  verbosity: minimal

test_script:
  - dir build
  - .\\%CONFIGURATION%\\app.exe
