name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: test
        run: |
          cd $GITHUB_WORKSPACE/pqalgo/test
          mkdir build && cd build
          cmake ..
          cmake --build .
          ./app
